[workspace]
resolver = "2"
members = [
    "yas",
    "genshin",
    "application",
    "experimental/hsr",
]
exclude = ["vendor/auto-artifactarium"]

[patch."https://github.com/konkers/auto-artifactarium"]
auto-artifactarium = { path = "vendor/auto-artifactarium" }

[profile.release]
lto = true
panic = "unwind"
strip = true
